packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': true
  argon2: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@nestjs/swagger@11.4.7'
